### ISSUE TITLE
Error running Quillman code with `modal serve src.app`

### ISSUE THREAD

**Issue by holyMolyTolli** [modal-labs/llammer#3]
Hi there,

I am experiencing an error running the code with modal serve src.app. Here is the error message:

```
Building image im-uapgkrskiwyzvdznvrsjdwytfles

=> Step 0: FROM base

=> Step 1: RUN cd /FastChat && python download-model.py anon8231489123/vicuna-13b-GPTQ-4bit-128g
Traceback (most recent call last):
  File "download-model.py", line 196, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch)
  File "download-model.py", line 130, in get_download_links_from_huggingface
    fname = dict[i]['path']
KeyError: 0
Terminating task due to error: command "cd /FastChat && python download-model.py anon8231489123/vicuna-13b-GPTQ-4bit-128g" had exit status: 1
```

Could you please help me identify the root cause of this error and provide guidance on how to fix it?

Thank you

**Comment by yoshinorisano** [comment]
I encountered the same error as well.

The root cause is that `download-model.py` does not work because HuggingFace appears to have changed their API, which no longer accepts an empty value for the `cursor` parameter.
https://github.com/thisserand/FastChat/blob/4a57c928a906705404eae06f7a44b4da45828487/download-model.py#L111

Here is a quick and simple workaround to fix this issue. I modified the code to manually download the necessary files, without using `download-model.py`.

```diff
diff --git a/src/llm_vicuna.py b/src/llm_vicuna.py
index c3b210a..8be1b92 100644
--- a/src/llm_vicuna.py
+++ b/src/llm_vicuna.py
@@ -12,7 +12,7 @@ from modal import Image, method
 from .common import stub
 
 MODEL_NAME = "anon8231489123/vicuna-13b-GPTQ-4bit-128g"
-
+MODEL_DIR = "anon8231489123_vicuna-13b-GPTQ-4bit-128g"
 
 stub.vicuna_image = (
     Image.from_dockerhub(
@@ -22,7 +22,7 @@ stub.vicuna_image = (
             "RUN apt-get install -y python3 python3-pip python-is-python3",
         ],
     )
-    .apt_install("git", "gcc", "build-essential")
+    .apt_install("git", "gcc", "build-essential", "wget")
     .run_commands(
         "git clone https://github.com/thisserand/FastChat.git",
         "cd FastChat && pip install -e .",
@@ -33,7 +33,14 @@ stub.vicuna_image = (
         "cd /FastChat/repositories/GPTQ-for-LLaMa && python setup_cuda.py install",
         gpu="any",
     )
-    .run_commands(f"cd /FastChat && python download-model.py {MODEL_NAME}")
+    .run_commands(f"mkdir /FastChat/models/{MODEL_DIR}")
+    .run_commands(f"cd /FastChat/models/{MODEL_DIR} && wget https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/resolve/main/config.json")
+    .run_commands(f"cd /FastChat/models/{MODEL_DIR} && wget https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/resolve/main/generation_config.json")
+    .run_commands(f"cd /FastChat/models/{MODEL_DIR} && wget https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/resolve/main/pytorch_model.bin.index.json")
+    .run_commands(f"cd /FastChat/models/{MODEL_DIR} && wget https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/resolve/main/special_tokens_map.json")
+    .run_commands(f"cd /FastChat/models/{MODEL_DIR} && wget https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/resolve/main/tokenizer.model")
+    .run_commands(f"cd /FastChat/models/{MODEL_DIR} && wget https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/resolve/main/tokenizer_config.json")
+    .run_commands(f"cd /FastChat/models/{MODEL_DIR} && wget https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/resolve/main/vicuna-13b-4bit-128g.safetensors")
 )
```

**Comment by aksh-at** [comment]
Thanks for the report @holyMolyTolli and for the diagnosis @yoshinorisano!
